// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv3rqv6evHJIo5hLB_IcdD0CNvCXyG-U4',
    appId: '1:431369985374:web:dffe97c1b6867b764143cf',
    messagingSenderId: '431369985374',
    projectId: 'pasar-atsiri-app',
    authDomain: 'pasar-atsiri-app.firebaseapp.com',
    storageBucket: 'pasar-atsiri-app.firebasestorage.app',
    measurementId: 'G-2DWH6D5GX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCady5juFw6m8oALljqrHopNv2g0bO4zlk',
    appId: '1:431369985374:android:ce2ee42e495521f64143cf',
    messagingSenderId: '431369985374',
    projectId: 'pasar-atsiri-app',
    storageBucket: 'pasar-atsiri-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPeqCH9bUXdj9YmmuSPKXQzYADSHvBvkw',
    appId: '1:431369985374:ios:52a72b7c4c21a2b84143cf',
    messagingSenderId: '431369985374',
    projectId: 'pasar-atsiri-app',
    storageBucket: 'pasar-atsiri-app.firebasestorage.app',
    iosBundleId: 'com.example.pasaratsiriApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPeqCH9bUXdj9YmmuSPKXQzYADSHvBvkw',
    appId: '1:431369985374:ios:52a72b7c4c21a2b84143cf',
    messagingSenderId: '431369985374',
    projectId: 'pasar-atsiri-app',
    storageBucket: 'pasar-atsiri-app.firebasestorage.app',
    iosBundleId: 'com.example.pasaratsiriApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv3rqv6evHJIo5hLB_IcdD0CNvCXyG-U4',
    appId: '1:431369985374:web:cb1929ce505a8f6f4143cf',
    messagingSenderId: '431369985374',
    projectId: 'pasar-atsiri-app',
    authDomain: 'pasar-atsiri-app.firebaseapp.com',
    storageBucket: 'pasar-atsiri-app.firebasestorage.app',
    measurementId: 'G-2RTRCC9EZM',
  );
}
